### ISSUE TITLE
NPE: Cannot read the array length because "thunkAddrs" is null

### ISSUE THREAD

**Issue by astrelsky** [Nalen98/GhidraEmu#1]
```
java.lang.NullPointerException: Cannot read the array length because "thunkAddrs" is null
	at ghidraemu.GhidraEmuProvider.getExternalAddresses(GhidraEmuProvider.java:766)
	at ghidraemu.GhidraEmuPlugin.programActivated(GhidraEmuPlugin.java:85)
	at ghidra.app.plugin.ProgramPlugin.processEvent(ProgramPlugin.java:138)
...
```

This occurred immediately upon activating the plugin for the first time. This was on a Ghidra 10.1 DEV build close to yet not exactly df50264a372b0fa39a244ed703c66cf30359ab08

https://github.com/Nalen98/GhidraEmu/blob/87bc034bdd92f385804507bb83d372229a8bad73/src/main/java/ghidraemu/GhidraEmuProvider.java#L759
It should be `&&` instead of `&`.

**Comment by Nalen98** [comment]
Greetings.
Sorry for precipitate and messy commit which was not a solution. I found an issue working with windows binaries and there was a problem with external functions which were not thunked. It concerns functions, for example, which were called by pointer or symbols marked by Ghidra as "pointer to external function". So now it's fixed and thanks pointing out the problem.

**Comment by astrelsky** [comment]
> Greetings.
> Sorry for precipitate and messy commit which was not a solution. I found an issue working with windows binaries and there was a problem with external functions which were not thunked. It concerns functions, for example, which were called by pointer or symbols marked by Ghidra as "pointer to external function". So now it's fixed and thanks pointing out the problem.

It's ok, I realize you are an intern and don't want to bombard you with a bunch of issues over little things. The cause of this issue though is the use of `&` instead of `&&`. While it may work in some cases it will not work when the first condition is a null check because it won't short circuit. A single `&` is bit wise and, `&&` is logical and.

**Comment by Nalen98** [comment]
Thank you. Yeah, that was a typo and I'm confused about this thing
