### ISSUE TITLE
GhidraEmuPlugin more compact layout

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/GhidraEmu#10]
Could you change GhidraEmuPlugin to have more compact layout ?
Idea is to have smaller space and buttons for Start / Step / Reset...

Proposal patch 
[GhidraEmuPlugin_More_Compact_Layout.zip](https://github.com/Nalen98/GhidraEmu/files/10325799/GhidraEmuPlugin_More_Compact_Layout.zip)
![image](https://user-images.githubusercontent.com/432709/210100288-10cf46c5-25d3-4823-bbcf-dc4d236d7747.png)

**Comment by Nalen98** [comment]
Thanks.

Was done in https://github.com/Nalen98/GhidraEmu/commit/ee617aa404bf97958eb42ec64e5a7830549f61cb

The minimal size I've got:

![Screenshot from 2022-12-31 01-15-03](https://user-images.githubusercontent.com/52778977/210115996-fb02faac-11cd-47de-98fa-caeb3470e7ad.png)
