### ISSUE TITLE
Can't set register value

### ISSUE THREAD

**Issue by wosk** [Nalen98/GhidraEmu#11]
The next step clears the set values in the registers

V850
Ghidra 10.2.2 PUBLIC
GhidraEmu 2.1

![Peek 2023-01-11 22-19](https://user-images.githubusercontent.com/1042932/211898287-be719eec-ac43-4b1d-9f6c-2ca217aa58e6.gif)

**Comment by Nalen98** [comment]
Thanks for the issue.
Fixed in https://github.com/Nalen98/GhidraEmu/commit/4d41f31a0f183a97c33a85ae1378ac5431e1a56b.

Now 8 byte registers like `r0r1` won't reset 4 byte registers (e.g., `r0` and `r1` in this case).
