### ISSUE TITLE
Unable to use it with 64bits 

### ISSUE THREAD

**Issue by hxm-cpp** [Nalen98/GhidraEmu#13]
![image](https://github.com/Nalen98/GhidraEmu/assets/116516702/6140f897-6310-4013-8844-705f2e1e6c79)

**Comment by Nalen98** [comment]
Please, attach a link to this binary that I could debug and solve this problem
I checked, and the plugin works correctly with 64-bit value addresses. In your case, I assume that your emulation process is located somewhere in non-DefaultAddressSpace.
