### ISSUE TITLE
GhidraEmu build error with ghidra_10.3_PUBLIC

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/GhidraEmu#14]
GhidraEmu build error with ghidra_10.3_PUBLIC
See errors in [ghidra_10_3_0_GhidraEmu_Errors.txt](https://github.com/Nalen98/GhidraEmu/files/11687229/ghidra_10_3_0_GhidraEmu_Errors.txt)

**Comment by Nalen98** [comment]
Thanks.
Fixed in https://github.com/Nalen98/GhidraEmu/commit/b5b5ef87356d76ae471fff0c1bfd6fb723b4a3d3
