### ISSUE TITLE
PluginInfo missing servicesRequired 

### ISSUE THREAD

**Issue by astrelsky** [Nalen98/GhidraEmu#2]
The `PluginInfo` annotation for `GhidraEmuPlugin` should have `servicesRequired` set to require the `ConsoleService` and `CodeViewerService` services that are used by `GhidraEmuProvider`. It is also currently possible to cause a NPE by clicking the reset button before ever starting the emulation because `console` has not yet been set. It would be better to set both `console` and `codeViewer` in the `GhidraEmuPlugin` constructor.

You would also need to move the initialization of `GhidraEmuPlugin.provider` to the `init` method.

**Comment by Nalen98** [comment]
I'm trying to set initialization of `console` and `codeViewer` in the constructor and getting nulls because `tool` can't get services in time. It's a right comment about reset and I throw setting of these in `programActivated` method. Tool will be set with all services and program is not null here.

**Comment by astrelsky** [comment]
> I'm trying to set initialization of `console` and `codeViewer` in the constructor and getting nulls because `tool` can't get services in time. It's a right comment about reset and I throw setting of these in `programActivated` method. Tool will be set with all services and program is not null here.

The tool can't get the services because they haven't been initialized yet. You need to set the `servicesRequired` field in `GhidraEmuPlugin`'s `PluginInfo` annotation. then move the following into the `init` method. https://github.com/Nalen98/GhidraEmu/blob/a3fed7404a45e5f714477d2903f789b0a07aa05b/src/main/java/ghidraemu/GhidraEmuPlugin.java#L52-L60

Ghidra plugins are first constructed, collected and then sorted in a `Collection` in order of the services they require and/or provide. Afterwards they each have their `init` method called so that they have all the services they require available to them. Moving the lines above into the `init` method and registering the required services in the `PluginInfo` annotation will ensure the services are available when the `GhidraEmuProvider` is constructed.

**Comment by Nalen98** [comment]
Thank you. Got it in https://github.com/Nalen98/GhidraEmu/commit/3a30f620df7ebca2bbf93011092167055bab3541.
