### ISSUE TITLE
Feature: Display different memory data wrote during emulation (RAM...)

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/GhidraEmu#4]
GhidraEmu is very interesting plugin to emulate code and check what happen in stack or register but unfortunately it does not allow to see change in RAM (not in stack)
Could you add that feature to display different section (RAM, SRAM....) ?

**Comment by Nalen98** [comment]
PCode instruction emulation really allows you to see where any bytes are written.

It's possible to create something similar to Ghidra's ByteViewer that will reflect all the changes that the write-to-mem instructions have made, are you talking about that?

**Comment by bvernoux** [comment]
Yes just to have a way to view all "memory" written with data value in HEX, ASCII ... like your view for the Stack memory

**Comment by Nalen98** [comment]
Hi! 
I worked on improvements, including this idea. It was possible to implement this in the new release.
https://github.com/Nalen98/GhidraEmu/releases/tag/2.0

Very briefly:
* Changed bytes during emulation will be displayed in the Ghidra's classic ByteViewer. GUI will be updated in this case too. The most of the time was spent handling/updating pointers and references. 
* If you want to change some bytes before/during emulation, don't forget to select them and press "Apply patched bytes". This will make it possible for the emulator to know about the changes that have occurred in memory and not to conflict in the future.

**Comment by bvernoux** [comment]
Thanks for that amazing feature implemented so quickly
