### ISSUE TITLE
Ghidra Emulation error on RISC-V (RV32-IMC) to write in memory display "Check out your emulation options, something wrong!"

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/GhidraEmu#7]
Ghidra Emulation error on RISC-V (RV32-IMC) to write in memory display "Check out your emulation options, something wrong!"

How to reproduce the issue:
1. With Ghidra 10.2.2 Load the elf from the archive [RISC-V-SecureDuo_Client_Top_Board.zip](https://github.com/Nalen98/GhidraEmu/files/10237644/RISC-V-SecureDuo_Client_Top_Board.zip)
2. At addr 0x00000000 decompile the first instruction (it is the entry it is mandatory to discover other function...)
3. Analysis->Auto Analyze ... => set "Aggressive Instruction Finder" and do the auto analysis
4. Navigation -> Goto => 0x2488
5. GhidraEMU Plugin set start to 0x2488
6. Step with GhidraEMU until 0x24ac where the issue appears with message box "Check out your emulation options, something wrong!"
Note: even if we fix gp for all the code with gp=20000c00 where the store in a3 will be at addr 20000514 (which is mapped) we have the same error
The fault appear on following asm line (even if a3 = 0x20000514)
`000024ac 98 c2           c.sw       a4,0x0(a3)`

![image](https://user-images.githubusercontent.com/432709/207881973-a90c244d-b184-4af5-9899-7aaef38c92ff.png)

![image](https://user-images.githubusercontent.com/432709/207881841-cc3ab48a-3bb6-4008-944c-b2f91b75b179.png)

**Comment by Nalen98** [comment]
Hello!

I have already started dealing with this issue.

> For information with latest version https://github.com/Nalen98/GhidraEmu/commit/c39ba4afa954ebe6b86a292da2edc9ee6b4296ba there is no any display "Check out your emulation options, something wrong!" just a freeze in Ghidra

Yes, I've fixed this at https://github.com/Nalen98/GhidraEmu/commit/9eda46718a23f63321f8cd1d75c51e9e411002de

**Comment by bvernoux** [comment]
> Hello!
> 
> I have already started dealing with this issue.
> 
> > For information with latest version [c39ba4a](https://github.com/Nalen98/GhidraEmu/commit/c39ba4afa954ebe6b86a292da2edc9ee6b4296ba) there is no any display "Check out your emulation options, something wrong!" just a freeze in Ghidra
> 
> Yes, I've fixed this at [9eda467](https://github.com/Nalen98/GhidraEmu/commit/9eda46718a23f63321f8cd1d75c51e9e411002de)

I have just rebuild myself the plugin with 9eda46718a23f63321f8cd1d75c51e9e411002de and I can always reproduce the freeze of Ghidra with same step as described before

**Comment by bvernoux** [comment]
I confirm it works with sp set to default 7ff7ff0
To reproduce the issue I have changed the Memory Map I just removed the auto created Stack (created by GhidraEMU) to use the real stack .stack renamed to Stack
So now the stack addr is at 0x20003800 to 0x20003ffff and that freeze Ghidra

**Comment by Nalen98** [comment]
Thanks for the info, I'll try to fix it. 

The original idea of creating the plugin and the underlying idea was that PCode emulation doesn't depend on the processor module and can be unified. The more I encounter such errors, the more I realize that each processor needs an individual approach.

**Comment by Nalen98** [comment]
https://github.com/Nalen98/GhidraEmu/commit/4c2f044b32d2ed6e4e799347210506779a832504

This commit will find the ".stack" section and use as the main stack space. The plugin initializes this section with 0x0 bytes (if it's not done) to avoid errors in the future.

**Comment by Nalen98** [comment]
I made some fixes for more clear emulation process, now the plugin will find the existing stack space and use it as the main one. I've set values of gp=20000c00 and a3=0x20000514 and got the error that referenced to uninitialized memory, which is a nice sign I guess:

![image](https://user-images.githubusercontent.com/52778977/207947758-b5c2a105-aa77-4d43-b9c2-f0dddc6f0612.png)

**Comment by Nalen98** [comment]
Hi, I've just tested this case which was described in the first comment. After a few of improvements, and here's I've got. 

Start address = 0x2488
gp = 20000c00
a3 = 20000514
-> Press "Run"

![image](https://user-images.githubusercontent.com/52778977/209451678-8eb985e8-8be7-4fbf-a672-354c5064c034.png)

The emulator ran to instruction at 0x2c30, which deals with uninitialized memory. Emulator can't create new memory blocks in Ghidra (it can take the existing block and init it with zeros, ".bss" for example). So we'll get the message:

`GhidraEmu> Uninitialized memory READ at pc = 00002c30 to address = ram:00003f24 with size = 4`

Can we say that the problem from the first comment is solved?

**Comment by bvernoux** [comment]
Thanks for your feedback I will cross check that on my side to have that memory initialized to check all work fine (when the addr is mapped)
Coul you push you correction to avoid the freeze and display an error because of emulation with the message "Uninitialized memory READ at pc = 00002c30 to address = ram:00003f24 with size = 4" when something like that happen ?

**Comment by Nalen98** [comment]
The screenshot from https://github.com/Nalen98/GhidraEmu/issues/7#issuecomment-1364587681 was taken according to the current master-branch of GhidraEmu (the latest commit https://github.com/Nalen98/GhidraEmu/commit/8075d5b1e6fa5c0584b688e7cd93a89c40253ddb "Lots of improvements and fixes"). At the moment, during testing, I haven't found the freeze, and such messages in the Ghidra console will appear in a timely manner.

**Comment by bvernoux** [comment]
Thanks for all I confirm latest version work fine now
