### ISSUE TITLE
Adding Step over feature?

### ISSUE THREAD

**Issue by dikidera** [Nalen98/GhidraEmu#9]
I am digging the emulator. What I have found is that it cannot step over subroutines. And a KEYBOARD button for faster stepping would be nice, like F11(hopefully it does not overlap with some Ghidra shortcut).

A small issue I have noticed is  that the plugin is not highlighting Delayed Branch instructions. Some architectures like SuperH have branching instructions, that execute the instructions after the branch and then branch to the target.

E.g 

`jsr <target>`
`mov 0x0, r4`

Here the mov is executed and only then does it branch. The emulator still works, still executes the instruction, only the highlighter does not highlight it.

The plugin is amazing however.

**Comment by Nalen98** [comment]
Hi! 

Thanks for your feedback. I will definitely deal with the highlighting delayed branch instructions problem.

Stepping over in a sense means to tell the emulator to run from a specific location A to location B. It can work nice if you set a breakpoint ("K" hotkey, "J" to remove) immediately after a long loop or subroutine, for example, then press the "Run" button and the emulator will automatically run and stop on this certain breakpoint. This will reduce the waiting time.

**Comment by dikidera** [comment]
Yes. And actually, this is how debuggers do it. They set an invisible(to the user) breakpoint. That's really what step over is.

**Comment by Nalen98** [comment]
In https://github.com/Nalen98/GhidraEmu/commit/8075d5b1e6fa5c0584b688e7cd93a89c40253ddb I've fixed the bug of highlighting delayed branch instruction (JSR). "Step Over" feature will be added as soon as possible. The new "Jump Over" feature that allows you to jump ahead one instruction if you don't want to emulate the current one for some reason, not related to this.

**Comment by Nalen98** [comment]
https://github.com/Nalen98/GhidraEmu/commit/05e73b3440e2db6704a8f1157179e10c53e164c4:
Step Over feature added

New Release 2.1:
https://github.com/Nalen98/GhidraEmu/releases/tag/2.1
